# Generated by Django 6.0.1 on 2026-01-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricApp', '0009_remove_orderitem_product_name_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
