# Generated by Django 6.0.1 on 2026-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricApp', '0013_cart_quantity_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(default='00000 00000', max_length=15),
        ),
    ]
