# Generated by Django 6.0.1 on 2026-04-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricApp', '0016_alter_brand_id_alter_cart_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
